sudo: true
language: python

os: "linux"

python:
  - "3.6"
  - "3.7"

before_install: pip install numpy cython multiprocess

install: python setup.py install

script: make

notifications:
  email: false
